### ISSUE TITLE
qcamera_test compile error

### ISSUE THREAD

**Issue by rancidfrog** [sonyxperiadev/camera#2]
```
hardware/qcom/camera/QCamera2/HAL/test/qcamera_test.cpp: In member function 'virtual void qcamera::CameraContext::notify(int32_t, int32_t, int32_t)':
hardware/qcom/camera/QCamera2/HAL/test/qcamera_test.cpp:822:59: error: 'CAMERA_FRAME_DATA_FD' was not declared in this scope
     if (( msgType & CAMERA_MSG_PREVIEW_FRAME) && (ext1 == CAMERA_FRAME_DATA_FD)) {
                                                           ^
build/core/binary.mk:620: recipe for target 'out/target/product/aries/obj/EXECUTABLES/camera_test_intermediates/qcamera_test.o' failed
```

**Comment by CoolDevelopment** [comment]
https://www.codeaurora.org/cgit/quic/la/platform/system/core/commit/?h=LA.BF64.1.1_rb1.43&id=9236335ee95ddf32a54a2a56e0ba7feb6dd0fc65
You need to apply this patch to build the camera hal.
But as far as i know there are some important parts missing to get camera working. Sony needs to release some parts of camera(proprietary qcom camera stack)

**Comment by jerpelea** [comment]
there is no need for this patch to build camera HAL 
i have started pushing all needed commits for building it
