### ISSUE TITLE
Z3+ dual e6533 camera can't focus on aosp 7.1.1

### ISSUE THREAD

**Issue by zzukylin** [sonyxperiadev/camera#63]
I build the aosp 7.1.1 for e6533,the back camera cant't focus and the front camera upside down.I take a picture ,there are green on the picture side.
Plase help me,if this is a bug please fix it soon,thank you~

This is the picture of back camera:
https://drive.google.com/open?id=0B7wrhrO2EGRXNU1oREhjMXdhUHc

**Comment by rcstar6696** [comment]
Only alin can fix the cam 
Cam blobs are closed source 
We need to wait for him

**Comment by zzukylin** [comment]
Ok,I will wait,thank you~ @rcstar6696

**Comment by bartcubbins** [comment]
@jerpelea outdated. Not the camera Hal issue

**Comment by TitanNano** [comment]
@bartcubbins @jerpelea I created a new build yesterday, exactly following the build instructions, using `android-7.1.1_r55` kernel `3.10` and the latest binaries `SW_binaries_for_Xperia_AOSP_M_MR1_3.10_v13_legacy`, but I'm still experiencing this issue. 
Is there any way this can be fixed?

**Comment by jerpelea** [comment]
Unfortunately there is no fix for Z3+ to improve the camera quality 
You can try to use "Open Camera" as an workaround (in settings you can try to enable API2)

**Comment by TitanNano** [comment]
@jerpelea API2 as introduced in Open Camera 1.24, I have 1.42 installed, but there is no API2 option. the old change log for v1.24 says that the option is only available if API2 is supported by the device. Is there anything that has to be done to try API2?

**Comment by jerpelea** [comment]
let me test and see if we can do anything on this legacy device

**Comment by TitanNano** [comment]
@jerpelea did you find anything that can be done?

**Comment by jerpelea** [comment]
I am sorry for my slow reply 

one solution should be to force HAL3 by editing the "persist.camera.HAL3.enabled" property to 1 in the following line https://github.com/sonyxperiadev/device-sony-common/blob/m-mr1/common.mk#L290

Then you should be able to use the advanced functions in the OpenCamera  app(in setting please enable API2)
