### ISSUE TITLE
D5503 / amami / Z1C - 7.1 AOSP build - Camera does not focus

### ISSUE THREAD

**Issue by MSe1969** [sonyxperiadev/camera#65]
Hi, 
might be related to Issue #63 - When building AOSP Nougat 7.1 for the Xperia Z1 compact following exactly the instructions here https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-nougat-for-unlocked-xperia-devices/ - the camera does not focus and is therefore not usable.
This is an issue also for other ROM developments (e.g. LOS) and seems to be caused by the camera blob. Please advise and help.
Thanks a lot, M.

**Comment by matthiasfostel** [comment]
Having same issue on 7.1.1 LOS.

**Comment by ragusa87** [comment]
I got the same problem with Android 6.0.1 on a Z5C (e5823)

**Comment by TitanNano** [comment]
@jerpelea when can this get fixed?

**Comment by TitanNano** [comment]
@MSe1969 @matthiasfostel I was able to work around this by installing Open Camera and playing around with the focus settings. Once I set it to macro, I got a sharp picture. Now it seems to work.

EDIT: It's also possible to set it back to auto and it still is able to focus.

**Comment by matthiasfostel** [comment]
I noticed the same thing. I tried Open Camera and changed the focus type several times from Continuous Picture to AutoFocus to I think "Infinite" (or something like that), and after a few seconds on AutoFocus the focus seemed to be working properly.

The only issue was that after a minute of doing this the battery was dropping like crazy to the point that the phone dropped off.

**Comment by bartcubbins** [comment]
@jerpelea outdated. Not the camera Hal issue
